name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:       # Allow manual runs

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Alvin-Zilverstand
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Amsterdam

          # 📅 Isometric commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
