name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight
  workflow_dispatch:       # Allow manual runs
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Alvin-Zilverstand
          outputs: dist/snake.svg
      - name: Push Snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "chore: update snake animation"
          add: "dist/snake.svg"
